env:
  node: true
  es2021: true
extends:
  - airbnb-base
plugins:
  - import
rules:
  no-console: off
  import/extensions: off
  linebreak-style: ["error", "windows"]
  import/prefer-default-export: off
  